version: "3.8"

services:
  # Backend (Node.js Application)
  backend:
    image: node:20-alpine
    container_name: text-editor
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    depends_on:
      - mongodb
      - bert-models
    command: npm start --prefix /app/backend
    network_mode: host
    volumes:
      - type: bind
        source: ./backend
        target: /app/backend
      - type: bind
        source: ./frontend
        target: /app/frontend

  # MongoDB
  mongodb:
    image: mongo:latest
    container_name: database
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    network_mode: host
    volumes:
      - type: bind
        source: .
        target: /app
      - type: bind
        source: ./mongodb
        target: /data/db

  # BERT models
  bert-models:
    build:
      context: ./models
    container_name: bert-models
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    network_mode: host
    working_dir: /app
    volumes:
      - type: bind
        source: ./models
        target: /app/models
      - type: bind
        source: ${HOME}/.cache/huggingface
        target: /root/.cache/huggingface
      - type: bind
        source: ./backend
        target: /app/backend
